language: java

# Our validator actually lives in the CKAN directory, which
# means CKAN-meta can stay nice and lightweight for then it
# gets downloaded by every single CKAN client. :)

install:
    - git clone https://github.com/KSP-CKAN/CKAN.git

# Our test is merely checking that all the ckan files validate
# against the current spec. We exclude the CKAN directory we just
# checked out.

script:
    - CKAN/bin/ckan-validate $(find . -path ./CKAN -prune -o -name '*.ckan' -print)

